[workspace]

members = [
    "packages/*",
    # "contracts/liquidity_hub/pool-network/terraswap_factory",
    # "contracts/liquidity_hub/pool-network/terraswap_pair",
    # "contracts/liquidity_hub/pool-network/terraswap_router",
    # "contracts/liquidity_hub/pool-network/terraswap_token",
    # "contracts/liquidity_hub/fee_collector",
    "contracts/liquidity_hub/vault-network/vault_factory/",
    "contracts/liquidity_hub/vault-network/vault",
    "contracts/liquidity_hub/vault-network/*",
]

[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/0xFable/cw-lint" },
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
